### ISSUE TITLE
Error API Animations

### ISSUE THREAD

**Issue by andfont** [miniaturepets/miniaturepets#132]
Version Server 1.14.4 spigot
Version Miniturepets 2.3.4
Description:
When you generate a miniture pets with the api da leaves the MOB but with errors, since version 2.13 this does not work and has not been solved and the incident has been deleted without being resolved because you delete it when it is a clear error !?

Example:
MobContainer estruc = APIUtils.loadContainer(model);
//Player pl = Bukkit.getPlayer("andfont");
Mob mob = new Mob(loc, estruc.getStructure(), EntityType.valueOf(mobabf.pandatipo));
//Mob mob = new Mob(pl.getLocation().add(0,1,0), estruc.getStructure(), EntityType.valueOf(mobabf.pandatipo));
mob.getNavigator().setHealth(mob.getNavigator().getMaxHealth());
mob.setSpeed(mobabf.pandavelocidad);
mob.setVisible(false);
mob.getNavigator().setAI(true);
mob.getNavigator().setCanPickupItems(true);
mob.getNavigator().setInvulnerable(false);
mob.getNavigator().setCustomName("PandaMobABF");
mob.setSilent(true);
mob.setCustomName(nombre);
mob.getPathManager().addPathfinder(new Panda(mob));
etc..
This has always worked well since 2.13 but always without the animation.

ERROR:
22:39:23 WARN]: [MiniaturePets] Task #541 for MiniaturePets v2.3.4 generated an exception
java.lang.NullPointerException: null
        at com.kirelcodes.miniaturepets.mob.Mob.isAnimationRunning(Mob.java:676) ~[?:?]
        at com.kirelcodes.miniaturepets.listener.CoreListener$1.run(CoreListener.java:79) ~[?:?]
        at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.14.4.jar:git-Paper-235]
        at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:452) ~[patched_1.14.4.jar:git-Paper-235]
        at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1171) ~[patched_1.14.4.jar:git-Paper-235]
        at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:417) ~[patched_1.14.4.jar:git-Paper-235]
        at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1098) ~[patched_1.14.4.jar:git-Paper-235]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:925) ~[patched_1.14.4.jar:git-Paper-235]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]

**Comment by andfont** [comment]
n the end I had to look at your code to fix the error, I have made my own version of your plugin so that it does not fail! but it is temporary waiting for you to solve it. The error is in your library code:
com.kirelcodes.miniaturepets.mob
public boolean isAnimationRunning () {
final Iterator <Map.Entry <String, AnimationCycle >> iterator = this.animation.entrySet (). iterator ();
while (iterator.hasNext ()) {
if (this.isAnimationRunning (iterator.next (). getKey ())) {
return true;
}
}

     // return false;
     // return this.moveCycle.isRunning ();
     // ABF We fix this temporary because we don't know the real reason
     try {moveCycle.isRunning ();} catch (Exception ex) {}
    
     return true;
 }
So far I have put this to avoid the error temporarily waiting for you to solve it! please regards.

**Comment by andfont** [comment]
it doesn't work! because you close if one is not working please do not close until it is really solved thanks

**Comment by Amokinio** [comment]
Hi @andfont,
I'm really sorry that your issue was not resolved. This issue is currently under review by our developers due to the fact that this issue was "technically" fixed. But don't worry, we may have made a mistake. As soon as the issue turns out to exist we will lift the **REVIEW** tag and fix it as soon as possible.

Sorry for all of the inconvenience,
@Amokinio.

_ORIGINAL: #107_

**Comment by Amokinio** [comment]
Also, please include your `/mpet dump` link.

**Comment by andfont** [comment]
- https://pastebin.com/LZkuwgjw
keep getting the error please fix this thanks!
- error:
13:25:04 WARN]: [MiniaturePets] Task #36 for MiniaturePets v2.3.6 generated an exception
java.lang.NullPointerException: null
        at com.kirelcodes.miniaturepets.listener.CoreListener$1.run(CoreListener.java:126) ~[?:?]
        at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.14.4.jar:git-Paper-239]
        at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:452) ~[patched_1.14.4.jar:git-Paper-239]
        at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1171) ~[patched_1.14.4.jar:git-Paper-239]
        at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:417) ~[patched_1.14.4.jar:git-Paper-239]
        at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1098) ~[patched_1.14.4.jar:git-Paper-239]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:925) ~[patched_1.14.4.jar:git-Paper-239]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_231]

**Comment by liorsl** [comment]
Hello,
The issue will be fixed in the next update. I will leave this issue open for the next few days if it will not work for you.

**Comment by andfont** [comment]
Thanks friend xD

**Comment by Amokinio** [comment]
Hi, Voigon made a tiny mistake because this issue will now be closed, I think this was fixed as we really spent some time on this one. Please, write me personally on discord if it was not, so we can further dig into the problem with your help.

Amokinio

**Comment by andfont** [comment]
IT HAS NOT OPERATED TO A DOES NOT WORK PLEASE DO NOT CLOSE the case does not work! Does the error still come out because you closed?
